# 1. Tuning 설정용 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-tuning-config
  namespace: jhhan
data:
  operatorTuning.yaml: |
    mainTuning:
      initializationRetryDelaySeconds: 5
      domainPresenceFailureRetryMaxCount: 5

---

# 2. WebLogic Operator용 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weblogic-operator-sa
  namespace: jhhan

---

# 3. Operator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weblogic-operator
  namespace: jhhan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weblogic-operator
  template:
    metadata:
      labels:
        app: weblogic-operator
    spec:
      serviceAccountName: weblogic-operator-sa
      containers:
      - name: operator
        image: ghcr.io/oracle/weblogic-kubernetes-operator:3.4.4
        imagePullPolicy: IfNotPresent
        command: ["java"]
        args:
          - "-Dweblogic.operator.verbose=true"
          - "-Dweblogic.operator.namespace=jhhan"
          - "-Dweblogic.operator.serviceaccount=weblogic-operator-sa"
          - "-Dweblogic.operator.externalRestEnabled=false"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-jar"
          - "/operator/weblogic-kubernetes-operator.jar"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - name: tuning-params
          mountPath: /deployment/operatorTuning.yaml
          subPath: operatorTuning.yaml
      volumes:
      - name: tuning-params
        configMap:
          name: operator-tuning-config
