apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-tuning-config
  namespace: jhhan
data:
  operatorTuning.yaml: |
    mainTuning:
      initializationRetryDelaySeconds: 5
      domainPresenceFailureRetryMaxCount: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weblogic-operator-sa
  namespace: jhhan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weblogic-operator
  namespace: jhhan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weblogic-operator
  template:
    metadata:
      labels:
        app: weblogic-operator
    spec:
      serviceAccountName: weblogic-operator-sa
      containers:
      - name: operator
        image: ghcr.io/oracle/weblogic-kubernetes-operator:3.4.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        command:
        - java
        args:
        - -jar
        - /operator/weblogic-kubernetes-operator.jar
        volumeMounts:
        - name: tuning-config
          mountPath: /deployment
      volumes:
      - name: tuning-config
        configMap:
          name: operator-tuning-config
