apiVersion: apps/v1
kind: Deployment
metadata:
  name: weblogic-operator
  namespace: jhhan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weblogic-operator
  template:
    metadata:
      labels:
        app: weblogic-operator
    spec:
      serviceAccountName: weblogic-operator-sa
      containers:
      - name: operator
        image: ghcr.io/oracle/weblogic-kubernetes-operator:3.4.4
        imagePullPolicy: IfNotPresent
        command: ["java"]
        args:
          - "-Dweblogic.operator.verbose=true"
          - "-Dweblogic.operator.namespace=jhhan"
          - "-Dweblogic.operator.serviceaccount=weblogic-operator-sa"
          - "-Dweblogic.operator.externalRestEnabled=false"
          - "-jar"
          - "/operator/weblogic-kubernetes-operator.jar"
        ports:
        - containerPort: 8080
        - containerPort: 8443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weblogic-operator-sa
  namespace: jhhan
