apiVersion: weblogic.oracle/v9
kind: Domain
metadata:
  name: sample-domain
  namespace: jhhan
spec:
  domainUID: sample-domain
  image: container-registry.oracle.com/middleware/weblogic:12.2.1.4
  imagePullPolicy: IfNotPresent
  webLogicCredentialsSecret:
    name: weblogic-credentials
  includeServerOutInPodLog: true
  logHomeEnabled: true
  logHome: /u01/oracle/user_projects/domains/sample-domain/logs
  serverStartPolicy: IF_NEEDED
  serverPod:
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms512m -Xmx1024m"
    volumeMounts:
    - mountPath: /u01/oracle/user_projects/domains/sample-domain/logs
      name: weblogic-logs
  adminServer:
    serverStartState: "RUNNING"
    adminService:
      channels:
      - channelName: default
        nodePort: 30012
    serverPod:
      ports:
      - name: default
        containerPort: 7001
  managedServers:
  - serverName: test_server1
    serverStartState: "RUNNING"
    serverPod:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker1
      ports:
      - name: default
        containerPort: 8001
        hostPort: 8001
  - serverName: test_server2
    serverStartState: "RUNNING"
    serverPod:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker2
      ports:
      - name: default
        containerPort: 8001
        hostPort: 8001
  configuration:
    introspectorJobActiveDeadlineSeconds: 900
  replicas: 2
---
apiVersion: v1
kind: Secret
metadata:
  name: weblogic-credentials
  namespace: jhhan
type: Opaque
data:
  username: d2VibG9naWM=        # weblogic
  password: d2VsY29tZTE=        # welcome1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblogic-logs
  namespace: jhhan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
