apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "apache.fullname" . }}
    release: "{{ .Release.Name }}"
spec:
  type: NodePort
  selector:
    app: {{ template "apache.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - port: 80
      nodePort: {{ .Values.httpNodePort }}
      name: rest-https

