# Copyright 2017, 2018, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
apiVersion: batch/v1
kind: Job
metadata:
  name: %DOMAIN_UID%-create-weblogic-sample-domain-job
  namespace: %NAMESPACE%
spec:
  template:
    metadata:
      labels:
        weblogic.resourceVersion: domain-v1
        weblogic.domainUID: %DOMAIN_UID%
        weblogic.domainName: %DOMAIN_NAME%
        app: %DOMAIN_UID%-create-weblogic-sample-domain-job
    spec:
      restartPolicy: Never
      containers:
        - name: create-weblogic-sample-domain-job
          image: %WEBLOGIC_IMAGE%
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
          volumeMounts:
          - mountPath: %CREATE_DOMAIN_SCRIPT_ROOT%
            name: create-weblogic-sample-domain-job-cm-volume
          - mountPath: %DOMAIN_ROOT_DIR%
            name: weblogic-domain-storage-volume
          - mountPath: /weblogic-operator/secrets
            name: weblogic-credentials-volume
          command: ["/bin/sh"]
          args: ["%CREATE_DOMAIN_SCRIPT_ROOT%/%CREATE_DOMAIN_SCRIPT%"]
          env:
            - name: DOMAIN_ROOT_DIR
              value: %DOMAIN_ROOT_DIR%
            - name: DOMAIN_HOME_DIR
              value: %DOMAIN_ROOT_DIR%/domain/%DOMAIN_NAME%
            - name: DOMAIN_LOGS_DIR
              value: %DOMAIN_ROOT_DIR%/logs
      volumes:
        - name: create-weblogic-sample-domain-job-cm-volume
          configMap:
            name: %DOMAIN_UID%-create-weblogic-sample-domain-job-cm
          %EXTRA_CM_PREFIX%configMap:
            %EXTRA_CM_PREFIX%name: %DOMAIN_UID%-create-weblogic-sample-domain-job-cm-extra
        - name: weblogic-domain-storage-volume
          persistentVolumeClaim:
            claimName: %DOMAIN_PVC_NAME%
        - name: weblogic-credentials-volume
          secret:
            secretName: %WEBLOGIC_CREDENTIALS_SECRET_NAME%
      %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%imagePullSecrets:
      %WEBLOGIC_IMAGE_PULL_SECRET_PREFIX%- name: %WEBLOGIC_IMAGE_PULL_SECRET_NAME%
