# This is an example of how to set up the Secret with the WebLogic Admin credentials.
# Please note that this method used encoded, but not encrypted data.
# We recommend that you use the command line alternative from a secure environment instead,
# i.e. kubectl create secret ...
apiVersion: v1
kind: Secret
metadata:
  # Note that this MUST match the name defined above in the Domain Custom Resource
  name: domain1-weblogic-credentials
type: Opaque
data:
  # data is base64 encoded like this: `echo -n "weblogic" | base64`
  # In this example, username is weblogic, password is welcome1
  username: d2VibG9naWM=
  password: d2VsY29tZTE=